### ISSUE TITLE
visualization issues in cluster and local meachine

### ISSUE THREAD

**Issue by albertleemon** [MLDataAnalytics/pNet#2]
Hi, Prof. Fan and Dr. Ma, 

Many thanks for your great tool. I have managed to run pNet in our slurm system. However, the pipeline can not be fully completed. It seems the error comes from the visualization function. Here is the log file for debugging. Could you please review it and give me suggestions on how to run the visualization properly? 

1. $ cat pnet/Data_Input/Script/cluster_job_workflow.log
Start time : 2024-09-08-17:56:09
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
All setups are finished.
Start to run
Start FN computation using PyTorch at 2024-09-08 17:56:57
Settings are loaded from folder Data_Input, FN_Computation and Cluster
Brain template is loaded from folder Data_Input
FN computation uses spatial-regularized non-negative matrix factorization method
load precomputed gFNs
Start to compute pFNs at 2024-09-08 17:56:59
Finished FN computation at 2024-09-08 17:57:50
Start QC at 2024-09-08 17:57:50
Finished QC at 2024-09-08 17:58:50
Start Visualization at 2024-09-08 17:58:50

2104579
--> Found 0 finished jobs out of 1 at 2024-09-08 17:58:51

After checking the job of 2104579, I got the log file. 
$ cat pnet/Group_FN/cluster_job_visualization.log
Start time : 2024-09-08-17:59:10
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
2024-09-08 17:59:52.220 (  12.824s) [    145C94EA5200]vtkXOpenGLRenderWindow.:456    ERR| vtkXOpenGLRenderWindow (0x55bfd50dc1e0): bad X server connection. DISPLAY=:0. Aborting.

/var/spool/slurm/d/job2104579/slurm_script: line 13: 602739 Aborted                 (core dumped) /cluster/intel/oneapi-2023.1.0/intelpython/latest/bin/python pnet/Group_FN/cluster_job_visualization.py
Finished time : 2024-09-08-17:59:52

3. then I tried to rerun with "unset Display", I got the same error. 

4. I tried to copy the code out and run it on a local machine as 
```
# Run gFN and pFN visualization
pnet.run_gFN_Visualization(dir_pnet_result)
pnet.run_pFN_Visualization(dir_pnet_result)
```

run_gFN_Visualization works well. But the run_pFN_Visualization crashed every 1.5 subjects (one subject plus ten more fig for the next one). 
I have 64GB of memory on my local machine.  

In addition, here is the suggestion from ChatGPT on the error from cluster_job_visualization.log.
_The error you're encountering seems to be related to an issue with the X server connection when attempting to run a visualization script using VTK (specifically vtkXOpenGLRenderWindow). The error message indicates that the DISPLAY environment variable is not set, which is essential for rendering graphics on systems that require X11 forwarding.

Use Offscreen Rendering:

If you don't have access to an X server (e.g., in a headless environment like many HPC clusters), you can switch to offscreen rendering. VTK has support for offscreen rendering, which allows you to render images without needing an active display. You can modify your script to enable offscreen rendering:

```
import vtk
render_window = vtk.vtkRenderWindow()
render_window.SetOffScreenRendering(1)  # Enable offscreen rendering_
```

Looking forward to your comments
Yours sincerely
Meng

**Comment by MLDataAnalytics** [comment]
Thank you for providing such a detailed description of the problem. I will take a look at the cluster computing issues. For the run on your local machine, do you have any crash log?

**Comment by MLDataAnalytics** [comment]
Please try to install VTK with osmesa (off-screen MESA): 
`conda install -c conda-forge "vtk>=9.2=*osmesa*"`

Hopefully, this will solve the visualization problems associated with cluster computing.

**Comment by albertleemon** [comment]
Thank you for your fast reply. It is a problem of vtk-osmesa related issues. 
However, there are issues with properly installing packages via conda in our cluster. But I successfully managed it via pip
`pip install --extra-index-url https://wheels.vtk.org vtk-osmesa`

It works perfectly fine for the visualization now.
Many thanks for your great help.

**Comment by MLDataAnalytics** [comment]
Thank you so
