### ISSUE TITLE
How to undersatnd the values saved in the FN.mat and TC.mat

### ISSUE THREAD

**Issue by albertleemon** [MLDataAnalytics/pNet#4]
Dear Prof. Fan, Dr. Ma

Hi, I have a short question about understanding the values in FN.mat and TC.mat in the Personalized_FN.
Here is an example: 
```
>> whos
  Name          Size              Bytes  Class     Attributes

  FN        59412x17            8080032  double              
  TC          450x17              61200  double 
```
As Cui described in his paper (Cui et al., 2022),  "For each person, we created a probabilistic (soft) network atlas, where each vertex had 17 loadings quantifying the extent to which this vertex belongs to each network."  So, FN.mat saves the probability of a voxel belonging to each network, while TC.mat saves the probability of each network at each TR. Am I right? 

Have the following conditions been considered well in the generated FN and TC? 
1). For a voxel, which is involved in multiple networks occasionally, 
or 2). The values of various networks involved in brain activity in some TRs. Is the sum of the probability in each TR equal to 1, or is it not necessary?

I am excited to hear your confirmation.
Yours sincerely
Meng

**Comment by MLDataAnalytics** [comment]
FN contains the loadings of individual functional networks. In the example data, there are 59,412 vertices and 17 functional networks. The loadings represent the probability values of voxels being assigned to each individual functional network. The functional networks can overlap with each other. An illustration of the overlapping functional networks is Fig. 9D (https://sciencedirect.com/science/article/pii/S1053811917303944).

TC contains the time courses corresponding to the functional networks. These can be interpreted as representative time courses of the functional networks. Their values reflect the brain activity levels of their corresponding functional networks, but the sum of the time courses of all functional networks does not necessarily equal 1 at each TR.

I hope the above information helps clarify your concerns. Thank you for your questions.

**Comment by albertleemon** [comment]
Thank you very much for the rapid feedback. It is very helpful.
